base/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static
from .views import (
    Logueo,
    PaginaRegistro,
    main_page,
    agregar_alimento,
    registro_diario,
    perfil_nutricional,
    analisis_nutricional,
    listar_alimentos,
    editar_alimento,
    eliminar_alimento,
    sugerencias_alimentos,
    listar_usuarios_inactivos,
    listar_todos_alimentos,
    agregar_nutriente_a_alimento,
    agregar_nutriente,
    listar_nutrientes,
    editar_nutriente,
    eliminar_nutriente,
    editar_nutriente_de_alimento,
    eliminar_nutriente_de_alimento
)

urlpatterns = [
    path('', Logueo.as_view(), name='login'),
    path('registro/', PaginaRegistro.as_view(), name='registro'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('main_page/', main_page, name='main_page'),
    path('agregar_alimento/', agregar_alimento, name='agregar_alimento'),
    path('registro_diario/', registro_diario, name='registro_diario'),
    path('perfil_nutricional/', perfil_nutricional, name='perfil_nutricional'),
    path('analisis_nutricional/', analisis_nutricional, name='analisis_nutricional'),
    path('listar_alimentos/', listar_alimentos, name='listar_alimentos'),
    path('editar_alimento/<int:alimento_id>/', editar_alimento, name='editar_alimento'),
    path('eliminar_alimento/<int:alimento_id>/', eliminar_alimento, name='eliminar_alimento'),
    path('sugerencias_alimentos/', sugerencias_alimentos, name='sugerencias_alimentos'),
    path('listar-usuarios-inactivos/', listar_usuarios_inactivos, name='lista_usuarios_inactivos'),
    path('super/listar_todos_alimentos/', listar_todos_alimentos, name='listar_todos_alimentos'),
    path('super/agregar_nutriente_a_alimento/<int:alimento_id>/', agregar_nutriente_a_alimento,
         name='agregar_nutriente_a_alimento'),
    path('agregar_nutriente/', agregar_nutriente, name='agregar_nutriente'),
    path('listar_nutrientes/', listar_nutrientes, name='listar_nutrientes'),
    path('editar_nutriente/<int:nutriente_id>/', editar_nutriente, name='editar_nutriente'),
    path('eliminar_nutriente/<int:nutriente_id>/', eliminar_nutriente, name='eliminar_nutriente'),
    path('super/editar_nutriente_de_alimento/<int:alimento_id>/<int:relacion_id>/',
         editar_nutriente_de_alimento, name='editar_nutriente_de_alimento'),

    path('super/eliminar_nutriente_de_alimento/<int:alimento_id>/<int:relacion_id>/',
         eliminar_nutriente_de_alimento, name='eliminar_nutriente_de_alimento')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

NIVEL_ACTIVIDAD_CHOICES = [
    ('sedentario', 'Sedentario'),
    ('ligero', 'Ligero'),
    ('moderado', 'Moderado'),
    ('intenso', 'Intenso'),
    ('muy_intenso', 'Muy Intenso'),
]

# Modelo Nutriente
class Nutriente(models.Model):
    TIPO_CHOICES = [
        ('vitamina', 'Vitamina'),
        ('mineral', 'Mineral'),
    ]
    nombre = models.CharField(max_length=255)
    tipo = models.CharField(max_length=8, choices=TIPO_CHOICES)

    def __str__(self):
        return self.nombre

class Alimento(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)  # Added this line to associate each food item with a user.
    nombre = models.CharField(max_length=255)
    calorias = models.DecimalField(max_digits=6, decimal_places=2)
    proteinas = models.DecimalField(max_digits=6, decimal_places=2)
    carbohidratos = models.DecimalField(max_digits=6, decimal_places=2)
    grasas = models.DecimalField(max_digits=6, decimal_places=2)
    descripcion = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to='alimentos_imagenes/', null=True, blank=True)
    nutrientes = models.ManyToManyField(Nutriente, through='AlimentoNutriente')  # Relación ManyToMany agregada

    def __str__(self):
        return self.nombre

# Modelo intermedio AlimentoNutriente
class AlimentoNutriente(models.Model):
    alimento = models.ForeignKey(Alimento, on_delete=models.CASCADE)
    nutriente = models.ForeignKey(Nutriente, on_delete=models.CASCADE)
    cantidad = models.DecimalField(max_digits=6, decimal_places=2)
    unidad = models.CharField(max_length=20)  # ej: mg, mcg, UI...

    def __str__(self):
        return f"{self.alimento.nombre} - {self.nutriente.nombre}"

class PerfilNutricional(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    edad = models.PositiveIntegerField()
    sexo = models.CharField(max_length=10, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')])
    peso = models.DecimalField(max_digits=6, decimal_places=2)
    altura = models.DecimalField(max_digits=6, decimal_places=2)
    nivel_actividad = models.CharField(max_length=50, choices=NIVEL_ACTIVIDAD_CHOICES)

    def __str__(self):
        return self.usuario.username

class RegistroDiario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    alimento = models.ForeignKey(Alimento, on_delete=models.CASCADE)
    fecha = models.DateField(auto_now_add=True)
    cantidad = models.DecimalField(max_digits=6, decimal_places=2)  # Puede ser por gramos, porciones, etc.

    def __str__(self):
        return f"{self.usuario.username} - {self.alimento.nombre} - {self.fecha}"

base/forms.py
from django import forms
from .models import Alimento, RegistroDiario, PerfilNutricional, AlimentoNutriente, Nutriente
from django.core.exceptions import ValidationError

class AlimentoForm(forms.ModelForm):
    class Meta:
        model = Alimento
        fields = ['nombre', 'calorias', 'proteinas', 'carbohidratos', 'grasas', 'descripcion', 'imagen']  # Esto incluirá todos los campos del modelo en el formulario

    def clean_calorias(self):
        data = self.cleaned_data['calorias']
        if data < 0:
            raise ValidationError("Las calorías no pueden ser negativas.")
        return data

    def clean_proteinas(self):
        data = self.cleaned_data['proteinas']
        if data < 0:
            raise ValidationError("Las proteínas no pueden ser negativas.")
        return data

    def clean_grasas(self):
        data = self.cleaned_data['grasas']
        if data < 0:
            raise ValidationError("Las grasas no pueden ser negativas.")
        return data

    def clean_carbohidratos(self):
        data = self.cleaned_data['carbohidratos']
        if data < 0:
            raise ValidationError("Los carbohidratos no pueden ser negativos.")
        return data

    # Hacer lo mismo para carbohidratos y grasas...
    # Continúa con esta lógica para otros campos que necesiten validación.

class RegistroDiarioForm(forms.ModelForm):
    class Meta:
        model = RegistroDiario
        fields = '__all__'
        exclude = ['usuario']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(RegistroDiarioForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['alimento'].queryset = Alimento.objects.filter(usuario=user)


class PerfilNutricionalForm(forms.ModelForm):
    class Meta:
        model = PerfilNutricional
        fields = ['edad', 'sexo', 'peso', 'altura', 'nivel_actividad']


class NutrienteForm(forms.ModelForm):
    class Meta:
        model = Nutriente
        fields = '__all__'


class AlimentoNutrienteForm(forms.ModelForm):
    class Meta:
        model = AlimentoNutriente
        fields = '__all__'
        exclude = ['alimento']

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Alimento, PerfilNutricional, RegistroDiario, Nutriente, AlimentoNutriente
from django.contrib.auth.decorators import login_required
from .utils import calcular_necesidades_nutricionales, analizar_ingesta_nutricional, calcular_bmr, ha_cumplido_limites, esta_por_sobrepasar_limites, MICRONUTRIENTES_ESENCIALES
from .forms import PerfilNutricionalForm, AlimentoForm, RegistroDiarioForm, NutrienteForm, AlimentoNutrienteForm
from django.db.models import Count
from datetime import date
from django.contrib import messages
from django.db.models import F
from django.shortcuts import get_object_or_404

@login_required
@user_passes_test(lambda u: u.is_superuser)
def listar_usuarios_inactivos(request):
    # Usuarios que no tienen registros
    usuarios_sin_registros = User.objects.annotate(num_registros=Count('registrodiario')).filter(num_registros=0, is_superuser=False)

    if request.method == 'POST':
        user_id = request.POST.get('user_id')
        usuario_a_eliminar = get_object_or_404(User, pk=user_id)

        if 'eliminar' in request.POST:
            return render(request, 'base/confirmar_eliminar_usuario.html', {'usuario': usuario_a_eliminar})
        elif 'confirmar_eliminar' in request.POST:
            usuario_a_eliminar.delete()
            return redirect('lista_usuarios_inactivos')

    return render(request, 'base/listar_usuarios_inactivos.html', {'usuarios_sin_registros': usuarios_sin_registros})



@login_required
@user_passes_test(lambda u: u.is_superuser)
def agregar_nutriente(request):
    if request.method == "POST":
        form = NutrienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('listar_nutrientes')
    else:
        form = NutrienteForm()
    return render(request, 'base/agregar_nutriente.html', {'form': form})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def listar_nutrientes(request):
    nutrientes = Nutriente.objects.all()
    return render(request, 'base/listar_nutrientes.html', {'nutrientes': nutrientes})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def editar_nutriente(request, nutriente_id):
    nutriente = get_object_or_404(Nutriente, id=nutriente_id)
    if request.method == "POST":
        form = NutrienteForm(request.POST, instance=nutriente)
        if form.is_valid():
            form.save()
            return redirect('listar_nutrientes')
    else:
        form = NutrienteForm(instance=nutriente)
    return render(request, 'base/editar_nutriente.html', {'form': form, 'nutriente': nutriente})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def eliminar_nutriente(request, nutriente_id):
    nutriente = get_object_or_404(Nutriente, id=nutriente_id)
    if request.method == "POST":
        nutriente.delete()
        return redirect('listar_nutrientes')
    return render(request, 'base/eliminar_nutriente.html', {'nutriente': nutriente})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def listar_todos_alimentos(request):
    alimentos = Alimento.objects.all()
    return render(request, 'base/listar_todos_alimentos.html', {'alimentos': alimentos})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def agregar_nutriente_a_alimento(request, alimento_id):
    alimento = get_object_or_404(Alimento, id=alimento_id)

    if request.method == "POST":
        # Assuming a form class named AlimentoNutrienteForm which handles the addition of nutrients to foods.
        form = AlimentoNutrienteForm(request.POST)
        if form.is_valid():
            nutriente_rel = form.save(commit=False)
            nutriente_rel.alimento = alimento
            nutriente_rel.save()
            return redirect('listar_todos_alimentos')

    else:
        form = AlimentoNutrienteForm()
    return render(request, 'base/agregar_nutriente_a_alimento.html', {'form': form, 'alimento': alimento})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def editar_nutriente_de_alimento(request, alimento_id, relacion_id):
    alimento = get_object_or_404(Alimento, id=alimento_id)
    relacion = get_object_or_404(AlimentoNutriente, id=relacion_id) # Asume que tienes un modelo llamado AlimentoNutriente

    if request.method == "POST":
        form = AlimentoNutrienteForm(request.POST, instance=relacion)
        if form.is_valid():
            form.save()
            return redirect('listar_todos_alimentos')

    else:
        form = AlimentoNutrienteForm(instance=relacion)
    return render(request, 'base/editar_nutriente_de_alimento.html', {'form': form, 'alimento': alimento})


@login_required
@user_passes_test(lambda u: u.is_superuser)
def eliminar_nutriente_de_alimento(request, alimento_id, relacion_id):
    alimento = get_object_or_404(Alimento, id=alimento_id)
    relacion = get_object_or_404(AlimentoNutriente,
                                 id=relacion_id)  # Nuevamente, asume que tienes un modelo llamado AlimentoNutriente

    if request.method == "POST":
        relacion.delete()
        return redirect('listar_todos_alimentos')

    return render(request, 'base/eliminar_nutriente_de_alimento.html', {'alimento': alimento, 'relacion': relacion})


class Logueo(LoginView):
    template_name = "base/login.html"
    field = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('main_page')  # Cambiado de 'tareas' a 'cotizar'


class PaginaRegistro(FormView):
    template_name = 'base/registro.html'
    form_class = UserCreationForm
    redirect_authtenticated_user = True
    success_url = reverse_lazy('main_page')  # Cambiado de 'tareas' a 'cotizar'

    def form_valid(self, form):
        usuario = form.save()
        if usuario is not None:
            login(self.request, usuario)
        return super(PaginaRegistro, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('main_page')  # Cambiado de 'tareas' a 'cotizar'
        return super(PaginaRegistro, self).get(*args, **kwargs)

@login_required
def main_page(request):
    return render(request, 'index.html')


@login_required
def agregar_alimento(request):
    if request.method == "POST":
        form = AlimentoForm(request.POST, request.FILES)
        if form.is_valid():
            alimento = form.save(commit=False)  # Guarda el alimento pero no lo comitees aún a la base de datos.
            alimento.usuario = request.user  # Asigna el usuario actual al alimento.
            alimento.save()  # Ahora guarda el alimento en la base de datos con el usuario asociado.
            return redirect('listar_alimentos')
    else:
        form = AlimentoForm()
    return render(request, 'base/agregar_alimento.html', {'form': form})


@login_required
def listar_alimentos(request):
    alimentos = Alimento.objects.filter(usuario=request.user)
    return render(request, 'base/listar_alimentos.html', {'alimentos': alimentos})


@login_required
def editar_alimento(request, alimento_id):
    alimento = get_object_or_404(Alimento, id=alimento_id)
    if request.method == "POST":
        form = AlimentoForm(request.POST, request.FILES, instance=alimento)
        if form.is_valid():
            form.save()
            return redirect('listar_alimentos')
    else:
        form = AlimentoForm(instance=alimento)
    return render(request, 'base/editar_alimento.html', {'form': form, 'alimento': alimento})


@login_required
def eliminar_alimento(request, alimento_id):
    alimento = get_object_or_404(Alimento, id=alimento_id)
    if request.method == "POST":
        alimento.delete()
        return redirect('listar_alimentos')
    return render(request, 'base/eliminar_alimento.html', {'alimento': alimento})


@login_required
def registro_diario(request):
    if request.method == "POST":
        form = RegistroDiarioForm(request.POST, user=request.user)
        form.instance.usuario = request.user
        if form.is_valid():
            registros = RegistroDiario.objects.filter(usuario=request.user, fecha=date.today())
            perfil = get_object_or_404(PerfilNutricional, usuario=request.user)
            necesidades = calcular_necesidades_nutricionales(perfil)
            analisis = analizar_ingesta_nutricional(registros, necesidades)

            # Obtener el alimento desde la base de datos
            alimento_obj = get_object_or_404(Alimento, id=form.cleaned_data['alimento'].id)
            alimento_info = {
                'calorias': alimento_obj.calorias,
                'proteinas': alimento_obj.proteinas,
                'carbohidratos': alimento_obj.carbohidratos,
                'grasas': alimento_obj.grasas,
                'cantidad': form.cleaned_data.get('cantidad', 1)  # Asumimos que 1 es el valor por defecto
            }

            if esta_por_sobrepasar_limites(analisis, necesidades, alimento_info):
                messages.warning(request, 'Este alimento te hará sobrepasar o alcanzar tus límites diarios.')
                return render(request, 'base/registro_diario.html', {'form': form})

            form.save()
            if ha_cumplido_limites(analisis, necesidades):
                messages.success(request, '¡Felicidades! Has cumplido con tu dosis diaria.')

            return redirect('analisis_nutricional')
    else:
        form = RegistroDiarioForm(user=request.user)
    return render(request, 'base/registro_diario.html', {'form': form})



@login_required
def perfil_nutricional(request):
    perfil, created = PerfilNutricional.objects.get_or_create(

base/templates/base/sugerencias_alimentos.html
{% load static %}
<html>

<style>
    .contact_section {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;  /* Asume todo el alto visible de la pantalla */
    }

    .form_container {
        width: 80%;  /* Puede ajustar esto según lo que necesites */
        margin: 0 auto;
    }

    .table thead th {
    background-color: #333; /* Adjust this color as needed */
    color: white; /* Color of the text */
    text-align: center; /* Center align the text */
    padding: 10px 5px; /* Adjust the padding as needed for vertical alignment */
    }

    .table tbody tr {
        background-color: #f9f9f9;  /* A light grey color */
        color: black;   /* Making text color black */
    }
</style>

<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>NutriVista - Agregar Alimento</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body class="sub_page">
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container ">
                    <a class="navbar-brand" href="{% url 'main_page' %}">
                        <span>
                            NutriVista
                        </span>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
                          <ul class="navbar-nav  ">
                            <li class="nav-item active">
                              <a class="nav-link" href="{% url 'main_page' %}">Home <span class="sr-only">(current)</span></a>
                            </li>
                            {% if user.is_superuser %}
                            <li class="nav-item ">
                              <a class="nav-link" href="{% url 'lista_usuarios_inactivos' %}"> Administrar Usuarios</a>
                            </li>
                            <li class="nav-item ">
                              <a class="nav-link" href="{% url 'listar_nutrientes' %}"> Administrar Nutrientes</a>
                            </li>
                            <li class="nav-item ">
                              <a class="nav-link" href="{% url 'listar_todos_alimentos' %}"> Administrar Alimentos</a>
                            </li>
                            {% endif %}
                            {% if not user.is_superuser %}
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'agregar_alimento' %}"> Agregar Alimento</a>
                            </li>
                              <li class="nav-item">
                              <a class="nav-link" href="{% url 'listar_alimentos' %}"> Listar Alimentos</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'registro_diario' %}"> Registro Diario</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'perfil_nutricional' %}"> Perfil Nutricional</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'analisis_nutricional' %}"> Análisis Nutricional</a>
                            </li>
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'sugerencias_alimentos' %}"> Recomendaciones</a>
                            </li>
                            {% endif %}
                            <li class="nav-item">
                              <a class="nav-link" href="{% url 'logout' %}"> Logout</a>
                            </li>
                          </ul>
                            <div class="user_option">
                                <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">
                                    <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
                                </form>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>


    <!-- análisis nutricional section -->
    <section class="contact_section ">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 px-0">
                    <div class="img-box">
                        <!-- Aquí puedes poner alguna imagen relevante para el análisis nutricional -->
                        <img src="{% static 'images/2317045.png' %}" alt="Imagen Análisis Nutricional">
                    </div>
                </div>
                <div class="col-lg-5 col-md-6">
                    <div class="form_container pr-0 pr-lg-5 mr-0 mr-lg-2">
                        <div class="heading_container">
                            <h2>
                                Resumen Nutricional y Sugerencias
                            </h2>
                        </div>

                        <!-- Aquí empieza el contenido de tu análisis nutricional -->
                        <div class="container mt-5">
                            <h2>Tu BMR: {{ bmr }} calorias</h2>
                            <table class="table table-bordered mt-4">
                                <thead>
                                    <tr>
                                        <th scope="col">Ítem</th>
                                        <th scope="col">Consumido</th>
                                        <th scope="col">Necesario</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>Calorías (Kcal)</td>
                                        <td>{{ analisis.calorias_consumidas }}</td>
                                        <td>{{ analisis.calorias_necesarias }}</td>
                                    </tr>
                                    <tr>
                                        <td>Proteínas (g)</td>
                                        <td>{{ analisis.proteinas_consumidas }}</td>
                                        <td>{{ analisis.proteinas_necesarias }}</td>
                                    </tr>
                                    <tr>
                                        <td>Carbohidratos (g)</td>
                                        <td>{{ analisis.carbohidratos_consumidas }}</td>
                                        <td>{{ analisis.carbohidratos_necesarios }}</td>
                                    </tr>
                                    <tr>
                                        <td>Grasas (g)</td>
                                        <td>{{ analisis.grasas_consumidas }}</td>
                                        <td>{{ analisis.grasas_necesarias }}</td>
                                    </tr>
                                </tbody>
                            </table>

                            <h3 class="mt-5">Recomendaciones</h3>
                            <ul>
                                {% for recomendacion in analisis.recomendaciones %}
                                    <li>{{ recomendacion }}</li>
                                {% endfor %}
                            </ul>


                            <h3 class="mt-5">Sugerencias de alimentos:</h3>
                            <ul>
                                {% for alimento in sugerencias_macro_micro %}
                                    <li>
                                        {{ alimento.nombre }} -
                                        Proteínas: {{ alimento.proteinas }},
                                        Carbohidratos: {{ alimento.carbohidratos }},
                                        Grasas: {{ alimento.grasas }}
                                        {% for nutriente in alimento.alimentonutriente_set.all %}
                                            - {{ nutriente.nutriente.nombre }}: {{nutriente.cantidad}} {{ nutriente.unidad }}
                                        {% endfor %}
                                        <div>
                                            <a href="{% url 'registro_diario'%}" class="btn btn-warning">Registrar Alimento</a>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- Aquí termina el contenido de tu análisis nutricional -->

                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- end agregar alimento section -->

    <!-- footer section -->
    <footer class="container-fluid footer_section">
        <p>
            &copy; 2023 All Rights Reserved. Design by NutriVista
            <a href="https://html.design/">Free Html Templates</a>
        </p>
    </footer>
    <!-- footer section -->

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>

</body>

</html>